### Classification Algorithms
- Iris Dataset

In [1]:
# load data
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocess 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

# Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Save model
import joblib

In [2]:
data = pd.read_csv('../../data/Iris.csv')
df = data.copy()
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

In [4]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
print("Missing values:", df.isna().sum())
print("Shape:", df.shape)
print('Duplicate values:', df.duplicated().sum())

Missing values: Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64
Shape: (150, 6)
Duplicate values: 0

In [6]:
X = df.drop('Species', axis=1)
y = df['Species']

In [7]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

In [9]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=200),
    "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=5),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "SVM": SVC(kernel='linear', probability=True, random_state=42)
}

In [10]:
results = []
trained_models = {}
conf_matrices = {}

for name, model in models.items():

    # Choose scaled data for algorithms that need it
    if name in ["Logistic Regression", "K-Nearest Neighbors", "SVM"]:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

    # Compute metrics
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='macro')
    rec = recall_score(y_test, y_pred, average='macro')
    f1 = f1_score(y_test, y_pred, average='macro')

    results.append({
        "Model": name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1 Score": f1
    })

    trained_models[name] = model

In [11]:
results_df = pd.DataFrame(results)
results_df = results_df.sort_values("Accuracy", ascending=False)
print("\nClassification Performance on Iris Dataset\n")
print(results_df)

Classification Performance on Iris Dataset

                 Model  Accuracy  Precision  Recall  F1 Score
0  Logistic Regression       1.0        1.0     1.0       1.0
1  K-Nearest Neighbors       1.0        1.0     1.0       1.0
2        Decision Tree       1.0        1.0     1.0       1.0
3                  SVM       1.0        1.0     1.0       1.0

In [12]:
# Best model
results_df = results_df.sort_values("Accuracy", ascending=False)
best_model_name = results_df.iloc[0]["Model"]
best_model = trained_models[best_model_name]
print("Best Model:", best_model_name)

joblib.dump(best_model, "../../models/classification_model.pkl")
print(f"\nBest model '{best_model_name}' saved successfully.")

Best Model: Logistic Regression

Best model 'Logistic Regression' saved successfully.